Repository jitt-team/fluent-calculations-primitives, pull requests merged in 2023-08, with the labels that each got.

#6 #3 GitHub Repository Structure Best Practices
  .github/workflows/dotnet.yml
  assets/fluent-calculations-github-banner.png
  assets/fluent-calculations-icon.ico
  assets/fluent-calculations-logo.png
  src/Fluent.Calculations.DotNetGraph/CalculationGraphRenderer.cs
  src/Fluent.Calculations.DotNetGraph/DotNetGraph.dll
  src/Fluent.Calculations.DotNetGraph/Fluent.Calculations.DotNetGraph.csproj
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsOne.cs
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsTwo.cs
  src/Fluent.Calculations.Primitives.Tests/Conditions/ConditionTests.cs
  src/Fluent.Calculations.Primitives.Tests/Expressions/ExpressionTranslatorTests.cs
  src/Fluent.Calculations.Primitives.Tests/Fluent.Calculations.Primitives.Tests.csproj
  src/Fluent.Calculations.Primitives.Tests/Graph/CalculationGraphTests.cs
  src/Fluent.Calculations.Primitives.Tests/Usings.cs
  src/Fluent.Calculations.Primitives.sln
  src/Fluent.Calculations.Primitives/ArgumentsList.cs
  src/Fluent.Calculations.Primitives/AssemblyInfo.cs
  src/Fluent.Calculations.Primitives/Calculation.cs
  src/Fluent.Calculations.Primitives/CalculationGraph.cs
  src/Fluent.Calculations.Primitives/Condition.cs
  src/Fluent.Calculations.Primitives/CreateValueArgs.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNode.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeComparison.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeConditional.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeConstant.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeMath.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionTranslator.cs
  src/Fluent.Calculations.Primitives/Fluent.Calculations.Primitives.csproj
  src/Fluent.Calculations.Primitives/IName.cs
  src/Fluent.Calculations.Primitives/IValue.cs
  src/Fluent.Calculations.Primitives/Number.cs
  src/Fluent.Calculations.Primitives/Tag.cs
  src/Fluent.Calculations.Primitives/TagsList.cs
  src/Fluent.Calculations.Primitives/Value.cs
Labels: enhancement

#5 DevOps: Push nuget to nuget.org
  .github/workflows/dotnet.yml
  src/Fluent.Calculations.DotNetGraph/Fluent.Calculations.DotNetGraph.csproj
  src/Fluent.Calculations.Primitives/Fluent.Calculations.Primitives.csproj
Labels: enhancement

#13 Address compile warnings 2023.08.22
  src/Fluent.Calculations.Primitives/Calculation.cs
  src/Fluent.Calculations.Primitives/CalculationGraph.cs
  src/Fluent.Calculations.Primitives/Condition.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeConditional.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionTranslator.cs
  src/Fluent.Calculations.Primitives/Number.cs
  src/Fluent.Calculations.Primitives/Tag.cs
  src/Fluent.Calculations.Primitives/Value.cs
Labels: technical-debt

#20 Change constructors visibility for easier extensibility
  src/Fluent.Calculations.Primitives/Number.cs
  src/Fluent.Calculations.Primitives/Tag.cs
  src/Fluent.Calculations.Primitives/Value.cs
Labels: enhancement

#22 Introduce SonarCloud Badges
  .github/README.md
Labels: continuous inspection, devops

#34 Changes to core concepts of Calculation<T> (#33)
  src/Fluent.Calculations.DotNetGraph/CalculationGraphRenderer.cs
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsOne.cs
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsTwo.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/CompostionTests.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Currency/Currency.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/Money.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/MoneyBuilder.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/ToMoney.cs
  src/Fluent.Calculations.Primitives.Tests/Graph/CalculationGraphTests.cs
  src/Fluent.Calculations.Primitives/Calculation.cs
  src/Fluent.Calculations.Primitives/Condition.cs
  src/Fluent.Calculations.Primitives/EvaluationContext.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionResultCache.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionTranslator.cs
  src/Fluent.Calculations.Primitives/IValue.cs
  src/Fluent.Calculations.Primitives/LamdaExpressionPrefixRemover.cs
  src/Fluent.Calculations.Primitives/Number.cs
  src/Fluent.Calculations.Primitives/Value.cs
Labels: enhancement

#35 DevOps: Introduce Nuget Badges
  .github/README.md
  src/Fluent.Calculations.DotNetGraph/Fluent.Calculations.DotNetGraph.csproj
  src/Fluent.Calculations.Primitives/Fluent.Calculations.Primitives.csproj
Labels: nuget

#37 Introducing limited compatibility with Generic Math
  src/Fluent.Calculations.DotNetGraph/CalculationGraphRenderer.cs
  src/Fluent.Calculations.DotNetGraph/Fluent.Calculations.DotNetGraph.csproj
  src/Fluent.Calculations.Primitives.Tests/BaseTypes/Condition/ConditionTests.cs
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsOne.cs
  src/Fluent.Calculations.Primitives.Tests/Calculation/CalculationTestsTwo.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/CompostionTests.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Currency/Currency.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/Money.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/MoneyBuilder.cs
  src/Fluent.Calculations.Primitives.Tests/Composition/Money/ToMoney.cs
  src/Fluent.Calculations.Primitives.Tests/DotNetGraph/CalculationGraphTests.cs
  src/Fluent.Calculations.Primitives.Tests/Expressions/ExpressionTranslatorTests.cs
  src/Fluent.Calculations.Primitives.Tests/Fluent.Calculations.Primitives.Tests.csproj
  src/Fluent.Calculations.Primitives.Tests/GenericMath/GenercMathTests.cs
  src/Fluent.Calculations.Primitives/ArgumentsList.cs
  src/Fluent.Calculations.Primitives/BaseTypes/ArgumentsCollection.cs
  src/Fluent.Calculations.Primitives/BaseTypes/Condition.cs
  src/Fluent.Calculations.Primitives/BaseTypes/CreateValueArgs.cs
  src/Fluent.Calculations.Primitives/BaseTypes/IName.cs
  src/Fluent.Calculations.Primitives/BaseTypes/IValue.cs
  src/Fluent.Calculations.Primitives/BaseTypes/Number.cs
  src/Fluent.Calculations.Primitives/BaseTypes/Tag.cs
  src/Fluent.Calculations.Primitives/BaseTypes/TagsCollection.cs
  src/Fluent.Calculations.Primitives/BaseTypes/Value.cs
  src/Fluent.Calculations.Primitives/CreateValueArgs.cs
  src/Fluent.Calculations.Primitives/EvaluationContext.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNode.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionNodeConditional.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionResultCache.cs
  src/Fluent.Calculations.Primitives/Expressions/ExpressionTranslator.cs
  src/Fluent.Calculations.Primitives/Expressions/LamdaExpressionPrefixRemover.cs
  src/Fluent.Calculations.Primitives/Fluent.Calculations.Primitives.csproj
  src/Fluent.Calculations.Primitives/IName.cs
  src/Fluent.Calculations.Primitives/Tag.cs
  src/Fluent.Calculations.Primitives/TagsList.cs
  src/Fluent.Calculations.Primitives/Utils/Enforce.cs
Labels: enhancement
